const DEFAULT_ITEMS = [
  {id:'d1',type:'وثيقة',category:'أوقاف',title:'صك وقفي موثق',author:'الإدارة',year:'1321 هـ',place:'منطقة جازان',desc:'نموذج أرشيفي لصك وقفي قديم، ضمن قسم الوثائق التي توثق الأوقاف والمصالح العامة والشهود.',src:'deed-1.jpg',media:'image'},
  {id:'d2',type:'وثيقة',category:'مبايعات',title:'أحد صكوك البيع والشراء القديمة',author:'الإدارة',year:'1349 هـ',place:'صبيا',desc:'وثيقة بيع وشراء قديمة تحفظ تفاصيل المبايعة، الأطراف، الشهود، وحدود الملكية.',src:'deed-2.jpg',media:'image'},
  {id:'d3',type:'وثيقة',category:'ملكية وأملاك',title:'صك أرض زراعية',author:'الإدارة',year:'1350 هـ',place:'صبيا',desc:'صك يوثق ملكية أرض زراعية قديمة مع بيانات الموقع والحدود، مخصص للعرض والقراءة الرقمية.',src:'deed-3.jpg',media:'image'},
  {id:'d4',type:'وثيقة',category:'مبايعات',title:'وثيقة مبايعة وشهود',author:'الإدارة',year:'1329 هـ',place:'المسارحة',desc:'وثيقة مبايعة تتضمن أسماء الشهود وتفاصيل المعاملة، وهي من أهم مواد الأرشيف التاريخي.',src:'deed-4.jpg',media:'image'},
  {id:'d5',type:'وثيقة',category:'مستندات مالية',title:'حجة استلام مبلغ',author:'الإدارة',year:'1352 هـ',place:'جازان',desc:'مستند مالي قديم يوثق استلام مبلغ ومعاملة بين أطراف، مع ختم/علامة أرشيفية واضحة.',src:'deed-5.jpg',media:'image'},
  {id:'d6',type:'وثيقة',category:'ملكية وأملاك',title:'وثيقة ملكية أرض',author:'الإدارة',year:'1363 هـ',place:'صبيا',desc:'صورة أرشيفية لصك ملكية أرض محفوظ ضمن أرشيف ذاكرة جازان للوثائق والصكوك.',src:'deed-6.jpg',media:'image'},
  {id:'d7',type:'وثيقة',category:'مبايعات',title:'مبايعة الشيخ علي بن عقلي',author:'الإدارة',year:'1336 هـ',place:'جازان',desc:'وثيقة مبايعة قديمة مضافة كنموذج ضمن قسم البيع والمبايعات.',src:'deed-10.jpg',media:'image'},
  {id:'d8',type:'وثيقة',category:'عقود ومعاملات',title:'وثيقة تقسيم ميراث',author:'الإدارة',year:'1340 هـ',place:'صبيا',desc:'نموذج لوثيقة معاملات أسرية/ملكية قديمة قابلة للتصنيف والبحث.',src:'deed-8.jpg',media:'image'},
  {id:'p1',type:'صورة',category:'صور تاريخية',title:'حياة القرية في جازان',author:'صور قديمة لزمن جميل',year:'1396 هـ / 1976م',place:'إحدى قرى جازان',desc:'صورة أرشيفية توثق بيوت العشش والمجالس الشعبية في إحدى قرى جازان.',src:'village-1396-color.png',media:'image'},
  {id:'p2',type:'صورة',category:'صور تاريخية',title:'قرية في جازان عام 1954م',author:'أرشيف بصري',year:'1373 هـ / 1954م',place:'إحدى قرى جازان',desc:'صورة قديمة يظهر فيها أحد الرحالة الغربيين وحوله أهل القرية وخلفهم بيوت العشش.',src:'village-1954.png',media:'image'},
  {id:'p3',type:'صورة',category:'هوية المشروع',title:'التصميم الأول لواجهة ذاكرة جازان',author:'الإدارة',year:'2026م',place:'ذاكرة جازان',desc:'تصميم مرجعي أولي لهوية الموقع وأسلوبه البصري.',src:'interface-first.png',media:'image'},
  {id:'p4',type:'صورة',category:'هوية المشروع',title:'واجهة تركّز على الوثائق والصكوك',author:'الإدارة',year:'2026م',place:'ذاكرة جازان',desc:'تصميم مرجعي للواجهة مع إبراز الوثائق والصكوك والبطاقات الأرشيفية.',src:'interface-docs-focus.png',media:'image'},
  {id:'r1',type:'صورة',category:'تهامة',title:'تهامة جازان',author:'هوية الموقع',year:'2026م',place:'تهامة جازان',desc:'خلفية وصورة تمثل السهل التهامي والقرى الزراعية والنخيل.',src:'region-tihama.png',media:'image'},
  {id:'r2',type:'صورة',category:'الجبال',title:'جبال جازان',author:'هوية الموقع',year:'2026م',place:'جبال جازان',desc:'صورة تمثل العمارة الجبلية والمدرجات الزراعية والمشهد الجبلي.',src:'region-mountains.png',media:'image'},
  {id:'r3',type:'صورة',category:'الساحل والجزر',title:'الساحل والجزر',author:'هوية الموقع',year:'2026م',place:'ساحل جازان',desc:'صورة تمثل الساحل والبحر والقوارب والمشهد الساحلي.',src:'region-coast.png',media:'image'},
  {id:'v1',type:'فيديو',category:'فيديوهات',title:'مقدمة أرشيف ذاكرة جازان',author:'الإدارة',year:'2026م',place:'جازان',desc:'فيديو قصير بصيغة عرض أرشيفي يدمج الهوية البصرية والصور القديمة.',src:'jazan-archive-intro.mp4',media:'video'},
  {id:'v2',type:'فيديو',category:'فيديوهات',title:'مشاهد من ذاكرة القرية',author:'الإدارة',year:'2026م',place:'جازان',desc:'فيديو قصير للصور التاريخية وقسم ذاكرة القرية.',src:'village-memory.mp4',media:'video'},
  {id:'m1',type:'منشور',category:'إعلان',title:'مرحبًا بكم في لوحة الذكريات',author:'إدارة ذاكرة جازان',year:'2026م',place:'الموقع',desc:'هذا القسم مخصص للمنشورات المشابهة للمنتديات والبلاك بورد. يمكن للإدارة إضافة صورة ونص مطول وعنوان واسم كاتب، لتظهر كذكرى أو إعلان أو قصة أرشيفية.',src:'logo-transparent-improved.png',media:'image'},
  {id:'m2',type:'منشور',category:'ذكريات وقصص',title:'ذاكرة من تهامة جازان',author:'إدارة الأرشيف',year:'2026م',place:'تهامة',desc:'خصصنا في هذه النسخة مساحة أوسع لصور تهامة والجبال والساحل، مع إمكان كتابة نص طويل مثل المنتديات لإضافة القصص والذكريات والشروحات حول الصور والوثائق.',src:'region-tihama.png',media:'image'},
  {id:'m3',type:'منشور',category:'مشاركات الأعضاء',title:'الجبال والساحل ضمن التقسيمات الرئيسية',author:'إدارة الأرشيف',year:'2026م',place:'جازان',desc:'يمكن استخدام لوحة الإدارة لإضافة منشورات عن الجبال أو الساحل والجزر، وإرفاق صورة أو فيديو مع النص، لتظهر داخل لوحة الذكريات وكذلك في آخر الإضافات.',src:'region-mountains.png',media:'image'}
];
function getItems(){try{return JSON.parse(localStorage.getItem('jm_items'))||DEFAULT_ITEMS}catch(e){return DEFAULT_ITEMS}}
function saveItems(items){localStorage.setItem('jm_items',JSON.stringify(items))}
function resetItems(){saveItems(DEFAULT_ITEMS)}
function byId(id){return getItems().find(x=>x.id===id)}
